
image: "rust:1.68"


stages:
  - test
  - publish

test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test --workspace


publish-crate:
  image: registry.gitlab.com/torkleyy/cargo-publish-all:latest
  stage: publish
  script:
    - cargo-publish-all --token $CRATES_IO_TOKEN --yes
  only:
    refs:
      - main
  when: manual

