name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ['1.80.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Run tests
        run: cargo test

      - name: Publish macros to crates.io
        working-directory: macros
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish DI to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}